print("=" * 50)
print("{:^30}".format("Factura"))
print("=" * 50)
print("\nNúmero de Factura: {:>30}")
print("Fecha de Emisión: {:>28}")
print("Cliente: {:>35}")
print("\nProductos:")
for producto in range(2):
    print("{:<30} {:>20}")
print("\nDescuento: {:>29}")
print("Total a Pagar: {:>29}")
print("=" * 50)